### ISSUE TITLE
Rule expected but "%" found  plugin/stylelint-bem-namics

### ISSUE THREAD

**Issue by tysonnero** [merkle-open/stylelint-bem#22]
## Type of issue

* Bug report

## Environment

- macOS Catalina 10.15.7
- darwin 19.6.0
- node 14.16.1
- npm 6.14.12

## Expected behavior

linter would allow Placeholder Selects, e.g. `%button { }`

## Current behavior

linter warns/errors with `Rule expected but "%" found  plugin/stylelint-bem-namics`

## Steps to reproduce the behavior

Run a placeholder selector through stylelint with the stylelint-bem plugin

```
%button {
  background-color: #000;
  color: #fff;
}
```

**Comment by ernscht** [comment]
Sorry, can't reproduce your issue.
Scss placeholders should work. 
The [test](https://github.com/merkle-open/stylelint-bem/blob/master/test/edge-cases.js#L16) also does not fail.

Can you give me more details? A test repo would of course be very helpful.

**Comment by ernscht** [comment]
Closed because problem cannot be reproduced.
