### ISSUE TITLE
Rule expected but "@" found 

### ISSUE THREAD

**Issue by Ivan-hl** [merkle-open/stylelint-bem#28]
Hello ! 

Sorry, My english is not good.

When I use lessOptions.modifyVars, I want to add prefix at one classname, but get this error.

Can you help me ?
![image](https://user-images.githubusercontent.com/42164477/203897869-75fef0c2-6913-48e8-b368-d28e525a8a5b.png)
![image](https://user-images.githubusercontent.com/42164477/203897908-2769238b-bf7b-4bbf-87ce-c066019bedb5.png)
![image](https://user-images.githubusercontent.com/42164477/203898050-bd7353b9-dca2-4759-a016-f7e3facbc836.png)

**Comment by ernscht** [comment]
Thanks for your question.

You're resuming an [earlier request](https://github.com/namics/stylelint-bem-namics/issues/13).
Unfortunately it is not possible to lint variable selectors. We do a static code analysis. That means that we are not able to inspect the variables value so we will not be able to calculate the final selector.

For cases like this, we recommend deactivating the plugin for this kind of selctors. e.g.

```
/* stylelint-disable-next-line plugin/stylelint-bem-namics */
.@{css-prefix}-wrapper {
  color: white;
}
```

**Comment by Ivan-hl** [comment]
I see.

Thank you for helping me solve the problem.
